// -----------------------------------------------------------------------
// <copyright file="ParadigmSkippedDataRowTestCase.cs" company="Leet">
//     Copyright (c) Leet. All rights reserved.
//     Licensed under the MIT License.
//     See License.txt in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

namespace Leet.Testing.Paradigmatic
{
    using System;
    using System.ComponentModel;
    using Xunit.Abstractions;
    using Xunit.Sdk;

    /// <summary>
    ///     Represents a test case that had a valid data row, but the data row was generated by a data attribute with the skip property set.
    /// </summary>
    public class ParadigmSkippedDataRowTestCase : XunitSkippedDataRowTestCase
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="ParadigmSkippedDataRowTestCase"/> class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
        public ParadigmSkippedDataRowTestCase()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="ParadigmSkippedDataRowTestCase"/> class.
        /// </summary>
        /// <param name="diagnosticMessageSink">
        ///     The message sink used to send diagnostic messages.
        /// </param>
        /// <param name="defaultMethodDisplay">
        ///     Default method display to use (when not customized).
        /// </param>
        /// <param name="testMethod">
        ///     The test method this test case belongs to.
        /// </param>
        /// <param name="skipReason">
        ///     The reason that this test case will be skipped.
        /// </param>
        /// <param name="testMethodArguments">
        ///     The arguments for the test method.
        /// </param>
        public ParadigmSkippedDataRowTestCase(
            IMessageSink diagnosticMessageSink,
            TestMethodDisplay defaultMethodDisplay,
            ParadigmTestMethod testMethod,
            string skipReason,
            object[] testMethodArguments = null)
            : base(diagnosticMessageSink, defaultMethodDisplay, testMethod, skipReason, testMethodArguments)
        {
        }

        /// <summary>
        ///     Gets the paradigm test method this test case belongs to.
        /// </summary>
        public ParadigmTestMethod ParadigmTestMethod
        {
            get
            {
                return this.TestMethod as ParadigmTestMethod;
            }
        }

        /// <summary>
        ///     Gets the display name for the test case.
        /// </summary>
        /// <param name="factAttribute">
        ///     The fact attribute the decorated the test case.
        /// </param>
        /// <param name="displayName">
        ///     The base display name from <see cref="TestMethodTestCase.BaseDisplayName"/>.
        /// </param>
        /// <returns>
        ///     The display name for the test case.
        /// </returns>
        protected override string GetDisplayName(IAttributeInfo factAttribute, string displayName)
        {
            string inheritedDisplayName = base.GetDisplayName(factAttribute, displayName);
            return ParadigmTestCase.ComposeDisplayName(inheritedDisplayName, this.BaseDisplayName, this.ParadigmTestMethod);
        }

        /// <summary>
        ///     Gets the unique ID for the test case.
        /// </summary>
        /// <returns>
        ///     The unique ID for the test case.
        /// </returns>
        protected override string GetUniqueID()
        {
            return ParadigmTestCase.ComposeUniqueId(base.GetUniqueID(), this.ParadigmTestMethod.Method.SutModificationMethod);
        }
    }
}
