//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leet.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leet.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fixture has been already assigned..
        /// </summary>
        internal static string Exception_InvalidOperation_FixtureAlreadyAssigned {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_FixtureAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use this objecct if no fixture is assigned to it..
        /// </summary>
        internal static string Exception_InvalidOperation_NoFixtureAssigned {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_NoFixtureAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test does not contain specification information..
        /// </summary>
        internal static string Exception_InvalidOperation_TestDoesNotContainSpecificationInfo {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_TestDoesNotContainSpecificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified member information parameter has an unexpected visibility..
        /// </summary>
        internal static string Exceptions_Argument_MemberInfoUnexpectedVisibility {
            get {
                return ResourceManager.GetString("Exceptions_Argument_MemberInfoUnexpectedVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified assembly defines more than one domain fixture type..
        /// </summary>
        internal static string Exceptions_Argument_MultipleDomainFixtures {
            get {
                return ResourceManager.GetString("Exceptions_Argument_MultipleDomainFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified assembly does not define domain fixture type..
        /// </summary>
        internal static string Exceptions_Argument_NoDomainFixture {
            get {
                return ResourceManager.GetString("Exceptions_Argument_NoDomainFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified type is not an interface type..
        /// </summary>
        internal static string Exceptions_Argument_NotInterfaceType {
            get {
                return ResourceManager.GetString("Exceptions_Argument_NotInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot contain a null item..
        /// </summary>
        internal static string Exceptions_Argument_NullCollectionItem {
            get {
                return ResourceManager.GetString("Exceptions_Argument_NullCollectionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be empty nor white space..
        /// </summary>
        internal static string Exceptions_Argument_StringWhiteSpaceOrEmpty {
            get {
                return ResourceManager.GetString("Exceptions_Argument_StringWhiteSpaceOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum exclusive count range must be greater than minimum inclusive count range..
        /// </summary>
        internal static string Exceptions_ArgumentOutOfRange_MaximumExclusiveCountRangeLessThanOrEqualToMinimum {
            get {
                return ResourceManager.GetString("Exceptions_ArgumentOutOfRange_MaximumExclusiveCountRangeLessThanOrEqualToMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum inclusive count range cannot be less than zero..
        /// </summary>
        internal static string Exceptions_ArgumentOutOfRange_MinimumInclusiveCountRangeNegative {
            get {
                return ResourceManager.GetString("Exceptions_ArgumentOutOfRange_MinimumInclusiveCountRangeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception has not been thrown..
        /// </summary>
        internal static string ExpectedExceptionNotThrownException_DefaultMessage {
            get {
                return ResourceManager.GetString("ExpectedExceptionNotThrownException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified type does not implement extension class correctly..
        /// </summary>
        internal static string InvalidExtensionClassImplementationException_DefaultMessage {
            get {
                return ResourceManager.GetString("InvalidExtensionClassImplementationException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration of the specified member has been found in the type but was not expected..
        /// </summary>
        internal static string MemberDeclarationNotExpectedException_DefaultMessage {
            get {
                return ResourceManager.GetString("MemberDeclarationNotExpectedException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration of the specified interface has not been found in the type..
        /// </summary>
        internal static string MissingInterfaceDeclarationException_DefaultMessage {
            get {
                return ResourceManager.GetString("MissingInterfaceDeclarationException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration of the specified member has not been found in the type..
        /// </summary>
        internal static string MissingMemberDeclarationException_DefaultMessage {
            get {
                return ResourceManager.GetString("MissingMemberDeclarationException_DefaultMessage", resourceCulture);
            }
        }
    }
}
